server:
  port: 7073
spring: 
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST=(ADDRESS = (PROTOCOL = TCP)(HOST = 10.61.2.11 )(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST =10.61.2.21 )(PORT = 1521))(LOAD_BALANCE=off)(FAILOVER=on))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = amc)))
    username: amc
    password: amc2O18cma
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 20 
      minimum-idle: 5
      connection-test-query: select 1 from dual
  redis:
    database: 0
    #host: 10.61.2.110
    #port: 6379
    timeout: 100000
    pool:
      max-active: 20
      max-idle: 10
      min-idle: 5
      max-wait: 10000
    sentinel:
      master: redis_master
      nodes: 10.61.2.110:26379,10.61.2.111:26379,10.61.2.112:26379
  activemq:
    broker-url: failover:(tcp://10.61.2.30:61616,tcp://10.61.2.31:61616)?randomize=false
    user: mq
    password: mq2O17
    pool:
      enabled: true
      max-connections: 20
      configuration:
        create-connection-on-startup: true
        maximum-active-session-per-connection: 100
  jms:
    template:
      qos-enabled: true
      delivery-mode: non-persistent
  application: 
    name: amc-sys-mc-service
management:
  security:
    enabled: false  
bmm:
  threadpool:
    corePoolSize: 100
    maxPoolSize: 200
    queueCapacity: 200
    keepAliveSeconds: 60
  testData: false
logging:
  level:
    root: info
 

mybatis:
  mapper-locations:
  - classpath:com.bjjdsy.amc.sys.mc.mapper/*.xml
  type-aliases-package: com.bjjdsy.amc.sys.mc.entity



        
socketConfig:
  port: 7073
  maxClient: 5000000
  heatBeatInterval: 60     
   